
###
GET http://localhost/book-service/api/books
Content-Type: application/json


###
GET http://127.0.0.1/api/avg-good
Content-Type: application/json






###
GET http://localhost/api/avg-bad
Content-Type: application/json