apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-connection-leak-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: springboot-connection-leak
  template:
    metadata:
      labels:
        component: springboot-connection-leak
    spec:
      containers:
        - name: springboot-connection-leak
          image: taaesan/app-db-leak
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-connection-leak-service
spec:
  type: ClusterIP
  selector:
    component: springboot-connection-leak
  ports:
    - port: 80
      targetPort: 8080