apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-db-leak-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: app-db-leak
  template:
    metadata:
      labels:
        component: app-db-leak
    spec:
      containers:
        - name: app-db-leak
          image: taaesan/app-db-leak:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-db-leak-service
spec:
  type: ClusterIP
  selector:
    component: app-db-leak
  ports:
    - port: 8080
      targetPort: 8080